// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJY8w2kjiZKIbxzZQOKVuVdBH0LEQU2lA',
    appId: '1:823162881269:web:dca6236157a204ac1bf1bc',
    messagingSenderId: '823162881269',
    projectId: 'fir-cloud-ac0e1',
    authDomain: 'fir-cloud-ac0e1.firebaseapp.com',
    storageBucket: 'fir-cloud-ac0e1.firebasestorage.app',
    measurementId: 'G-Q36DJRRC8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF4GTYRkrNXmUIX6c3uT2X2FD96WOQwEc',
    appId: '1:823162881269:android:1e095866b697ef101bf1bc',
    messagingSenderId: '823162881269',
    projectId: 'fir-cloud-ac0e1',
    storageBucket: 'fir-cloud-ac0e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW4AsYDYDiDQFwJwcAoDBmRteFkBzPGlo',
    appId: '1:823162881269:ios:b53148056414724f1bf1bc',
    messagingSenderId: '823162881269',
    projectId: 'fir-cloud-ac0e1',
    storageBucket: 'fir-cloud-ac0e1.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCloud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW4AsYDYDiDQFwJwcAoDBmRteFkBzPGlo',
    appId: '1:823162881269:ios:b53148056414724f1bf1bc',
    messagingSenderId: '823162881269',
    projectId: 'fir-cloud-ac0e1',
    storageBucket: 'fir-cloud-ac0e1.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCloud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJY8w2kjiZKIbxzZQOKVuVdBH0LEQU2lA',
    appId: '1:823162881269:web:a4b42756c173b9001bf1bc',
    messagingSenderId: '823162881269',
    projectId: 'fir-cloud-ac0e1',
    authDomain: 'fir-cloud-ac0e1.firebaseapp.com',
    storageBucket: 'fir-cloud-ac0e1.firebasestorage.app',
    measurementId: 'G-XQX95947F6',
  );
}
